export let commonCases1 = [
  "Hernia",
  "Replacement hip",
  "Replacement knee",
  "Gall bladder removal",
  "Oncology",
  "Kidney stones",
  "Urology",
  "Orthopaedics",
];
export let commonCases = [
  "Hernia",
  "Replacement hip",
  "Replacement knee",
  "Gall bladder removal",
  "Oncology",
  "Kidney stones",
  "Urology",
  "Orthopaedics",
  "Restorative dentistry",
  "Neurosurgery",
  "Tonsillectomy",
  "Paediatrics",
  "Audiology",
  "Opthalmology",
  "Dermatology",
  "Gastroenterology",
  "Haematology XXX",
];

export let commonCases2 = [
  "Restorative dentistry",
  "Neurosurgery",
  "Tonsillectomy",
  "Paediatrics",
  "Audiology",
  "Opthalmology",
  "Dermatology",
  "Gastroenterology",
  "Haematology XXX",
];

export let nhsWaitingLists = [
  "Hip & knee replacements 681,000",
  "eyes 574,000",
  "general & cancer 439,000",
  "gastroenterology 313,000",
  "urology 305,000",
  "skin 276,000",
  "heart 255,000",
  "oral & ENT 232,000",
  "neurology 196,000",
  "respiratory 124,000",
  "rheumatics 108,000",
  "other 1,173,000",
];

export let services = [
  "dental surgery",
  "orthopaedics",
  "bariatric surgery",
  "cataract surgery",
  "ophthalmology",
  "retinal surgery",
  "anterior cruciate ligament (ACL)",
  "meniscus tear",
  "maxillo-facial surgery",
  "dental implants",
  "posterior cruciate ligament (PCL)",
  "knee reconstruction",
  "spinal surgery",
  "slipped disc",
  "spinal disc replacement",
  "echo cardiogram",
  "MRI",
  "CT scan",
  "cardiac stent",
  "hip replacement",
  "abdominal hernia",
  "spinal hernia",
  "thyroidectomy",
  "dialysis",
  "heart bypass",
  "vena cava infusion",
  "hysterectomy",
  "endoscopic thoracic sympathectomy",
  "neurectomy",
  "biopsy (frozen section)",
  "tumour cell assay",
  "corneal transplant",
  "facial reconstruction",
  "angioplasty",
  "gall stones",
  "kidney stones",
  "urethroplasty",
  "phalloplasty",
  "tenotomy",
  "vasectomy",
  "hip revision",
  "vasovastostomy",
  "vasoepididymostomy (vasectomy reversal)",
  "fasciotomy",
  "breast implant",
  "IVF",
  "arthroplasty",
  "osteotomy",
  "laminotomy",
  "palatoplasty",
  "uvulopalatoplasty",
  "circumcision",
  "foreskin restoration",
  "z-plasty",
  "tubal ligation / reversal",
  "otoplasty",
  "trabeculoplasty (glaucoma)",
  "radial keratomy",
  "rhinoplasty",
  "septoplasty",
  "thymus transplant",
  "meatotomy",
  "foraminotomy",
  "breast reduction / augmentation",
  "hyperhydrosis",
  "arthritis",
  "abdominoplasty",
  "oncology",
  "liposuction",
  "gluteoplasty",
  "buttock lift",
  "aortic valve replacement (TAVR)",
  "pacemaker",
  "rheumatology",
  "physiotherapy",
  "nuclear medicine",
  "rehabilitation",
  "podiatry",
  "fascitis",
  "dermatology",
  "immunology",
  "ENT",
  "obstetrics",
  "allergy",
  "gastroenterology",
  "tennis elbow",
  "frozen shoulder",
  "marrow transplant",
  "genitourinary medicine",
  "sports medicine",
  "trauma",
  "neurophysiology",
  "thoracic surgery",
  "mastectomy",
  "",
  "orthodontics",
  "haemophilia",
  "stroke",
  "pallidotomy",
  "congenital disease",
  "interventional radiology",
  "stapedectomy",
  "respiratory tract",
  "lung disease",
  "anticoagulant",
  "phlebitis",
  "gout",
  "radiotherapy",
  "paarathyroidectomy",
  "photorefractive keratectomy",
  "spleen transplant",
  "haematology",
  "vertical banded gastroplasty",
  "kidney transplant",
  "spondylisis",
  "lithotripsy",
  "prostatectomy",
  "vasectomy",
  "achilles tendon",
  "dietetics",
  "carpal tunnel release",
  "cranial decompression",
  "acromioplasty",
  "greater trochanter fusion",
  "khyphoplasty",
  "tropical disease",
  "pain management",
  "artificial ankylosis",
  "ulnar collateral ligament construction (TJS)",
  "hepatology",
  "histology",
  "melanoma",
  "clinical depression",
  "reconstructive surgery",
  "ovarian cyst",
  "hormone replacement",
  "hyperthyroidism",
  "leukaemia",
  "gastric band",
  "presbyopia",
  "skin graft",
  "v-plasty",
  "pulmonary valve reconstruction",
  "eyelid surgery",
  "v-y-plasty",
  "quadriceps tendon reconstruction",
  "w-plasty",
  "rotator cuff surgery",
  "AFP tumour marker test",
  "spinal stenosis",
  "fluorescence guided surgery",
  "septoplasty",
  "Brostrom operation (ATFL)",
  "haemarrhoidectomy",
  "natural orifice ",
  "endoscopic surgery (NOTES)",
  "myomectomy (uterine fibroids)",
  "varicose vein repair",
];
